# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "374448357"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/arxiv-daily.json'
json_gitpage_path: './docs/arxiv-daily-web.json'
json_wechat_path: './docs/arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "DPI": 
        filters: ["SLAM", "Visual Odometry"]
    "DDI":
        filters: ["SFM", "Structure from Motion"]
    #"MG":
        #filters: ["Visual Localization",]
    #"MPP":
        #filters: ["Keypoint Detection",]
    "MD":
        filters: ["Molecular Dynamics Simulations", "Model ", ]
    
