# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "374448357"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 100

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/arxiv-daily.json'
json_gitpage_path: './docs/arxiv-daily-web.json'
json_wechat_path: './docs/arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "DTI": 
        filters: ["Drug Target Interactions"]
    "DDI":
        filters: ["Drug Drug Interactions"]
    "MG":
        filters: ["Molecular Generation", ]
    "MPP":
        filters: ["Molecular property prediction", "Self-Supervised", "Pre-Training"]
    "MD":
        filters: ["Molecular Dynamics Simulations"]
    "Transformer":
        filters: ["transformer", "deep learning"]
    "bind":
        filters: ["protein ligand bind", "docking"]
    
